name: CI

on: [push]
#  push:
#    branches:
#      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build and Test Frontend
        working-directory: packages/frontend
        run: |
          yarn build
          yarn test

      - name: Build and Test Backend
        working-directory: packages/backend  
        run: |
          yarn build
          yarn test